# Generated by Django 5.0.7 on 2024-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleradditional',
            name='Verification_Image',
            field=models.ImageField(default=None, upload_to='Seller_Verification'),
        ),
        migrations.AddField(
            model_name='selleradditional',
            name='Verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
