# Generated by Django 5.0.6 on 2024-07-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_order_order_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_subject',
            new_name='subject',
        ),
    ]
