# Generated by Django 5.0.7 on 2024-07-22 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_user_review_name_alter_review_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='timez',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
