# Generated by Django 5.0.6 on 2024-07-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_rename_name_review_user_alter_review_timez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='upload_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.selleradditional'),
        ),
    ]
