# Generated by Django 5.0.6 on 2024-07-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_art_upload_by'),
        ('Shop', 'fix_upload_by_fk'),
    ]

    operations = [
    ]
