# Generated by Django 5.0.6 on 2024-07-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_merge_0010_alter_art_upload_by_fix_upload_by_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='upload_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.selleradditional'),
        ),
    ]
