# Generated by Django 5.0.7 on 2024-07-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_art_upload_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_update',
            old_name='order_desc',
            new_name='order_Status',
        ),
        migrations.AlterField(
            model_name='art',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.selleradditional'),
        ),
    ]
