# Generated by Django 5.0.7 on 2024-07-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_rename_order_desc_order_update_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_update',
        ),
    ]
