# Generated by Django 5.0.7 on 2024-07-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_delete_order_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_Status', models.CharField(max_length=1000)),
                ('order_time', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_updates', to='Shop.order')),
            ],
        ),
    ]
