# Generated by Django 5.0.7 on 2024-07-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_order_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
