# Generated by Django 5.0.7 on 2024-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=70)),
                ('c_email', models.CharField(default='', max_length=75)),
                ('c_phone', models.CharField(default='', max_length=50)),
                ('c_subject', models.CharField(default='', max_length=100)),
                ('c_message', models.CharField(default='', max_length=1500)),
            ],
        ),
    ]
